###
POST https://store-builder-backend.onrender.com/api/signup/
Content-Type: application/json

{
    "email_phone": "zishan321@gmail.com",
    "password": "zish6708",
    "created_at": "2024-03-25",
    "site_name": "site",
    "category": "wordpress"
}

###
POST https://store-builder-backend.onrender.com/login/
Content-Type: application/json

{
    "email_phone": "zishan@gmail.com",
    "password": "zish6708"
}